# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/verilog/myproject/myproject.cache/wt [current_project]
set_property parent.project_path D:/verilog/myproject/myproject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/verilog/myproject/myproject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/verilog/myproject/coe/test.coe
read_verilog -library xil_defaultlib {
  D:/verilog/myproject/myproject.srcs/sources_1/CPU/CPU.srcs/sources_1/new/ADDER_PC.v
  D:/verilog/myproject/myproject.srcs/sources_1/new/ALU.v
  D:/verilog/myproject/myproject.srcs/sources_1/CPU/CPU.srcs/sources_1/new/HI_LO.v
  D:/verilog/myproject/myproject.srcs/sources_1/CPU/CPU.srcs/sources_1/new/MUX2.v
  D:/verilog/myproject/myproject.srcs/sources_1/CPU/CPU.srcs/sources_1/new/MUX3.v
  D:/verilog/myproject/myproject.srcs/sources_1/CPU/CPU.srcs/sources_1/new/MUX4.v
  D:/verilog/myproject/myproject.srcs/sources_1/CPU/CPU.srcs/sources_1/new/PC.v
  D:/verilog/myproject/myproject.srcs/sources_1/CPU/CPU.srcs/sources_1/new/REG_FILE.v
  D:/verilog/myproject/myproject.srcs/sources_1/CPU/CPU.srcs/sources_1/new/S_16.v
  D:/verilog/myproject/myproject.srcs/sources_1/CPU/CPU.srcs/sources_1/new/S_2.v
  D:/verilog/myproject/myproject.srcs/sources_1/new/adder.v
  D:/verilog/myproject/myproject.srcs/sources_1/new/clk1.v
  D:/verilog/myproject/myproject.srcs/sources_1/new/clk2.v
  D:/verilog/myproject/myproject.srcs/sources_1/new/clk3.v
  D:/verilog/myproject/myproject.srcs/sources_1/new/clk4.v
  D:/verilog/myproject/myproject.srcs/sources_1/new/conflict.v
  D:/verilog/myproject/myproject.srcs/sources_1/new/controller.v
  D:/verilog/myproject/myproject.srcs/sources_1/new/l_expand.v
  D:/verilog/myproject/myproject.srcs/sources_1/new/pc_sub_4.v
  D:/verilog/myproject/myproject.srcs/sources_1/new/r_expand.v
  D:/verilog/myproject/myproject.srcs/sources_1/new/submux.v
  D:/verilog/myproject/myproject.srcs/sources_1/new/valid.v
  D:/verilog/myproject/myproject.srcs/sources_1/new/myproject.v
}
read_ip -quiet D:/verilog/myproject/myproject.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
set_property used_in_implementation false [get_files -all d:/verilog/myproject/myproject.srcs/sources_1/ip/div_gen_0/div_gen_0_ooc.xdc]
set_property is_locked true [get_files D:/verilog/myproject/myproject.srcs/sources_1/ip/div_gen_0/div_gen_0.xci]

read_ip -quiet D:/verilog/myproject/myproject.srcs/sources_1/ip/div_gen_1/div_gen_1.xci
set_property used_in_implementation false [get_files -all d:/verilog/myproject/myproject.srcs/sources_1/ip/div_gen_1/div_gen_1_ooc.xdc]
set_property is_locked true [get_files D:/verilog/myproject/myproject.srcs/sources_1/ip/div_gen_1/div_gen_1.xci]

read_ip -quiet D:/verilog/myproject/myproject.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property used_in_implementation false [get_files -all d:/verilog/myproject/myproject.srcs/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc]
set_property is_locked true [get_files D:/verilog/myproject/myproject.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci]

read_ip -quiet D:/verilog/myproject/myproject.srcs/sources_1/ip/mult_gen_1/mult_gen_1.xci
set_property used_in_implementation false [get_files -all d:/verilog/myproject/myproject.srcs/sources_1/ip/mult_gen_1/mult_gen_1_ooc.xdc]
set_property is_locked true [get_files D:/verilog/myproject/myproject.srcs/sources_1/ip/mult_gen_1/mult_gen_1.xci]

read_ip -quiet D:/verilog/myproject/myproject.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/verilog/myproject/myproject.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files D:/verilog/myproject/myproject.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top cpu -part xc7a200tfbg676-2


write_checkpoint -force -noxdef cpu.dcp

catch { report_utilization -file cpu_utilization_synth.rpt -pb cpu_utilization_synth.pb }
